package Tests;

import LMS.*;
import org.junit.Before;
import org.junit.Test;

import static org.junit.Assert.*;

/**
 * Unit tests for Book class
 *
 * Tests focus on:
 * - Constructor and ID assignment
 * - Getters and setters
 * - Hold request management (unit-testable parts)
 *
 * Note: Methods like issueBook() and returnBook() involve complex interactions
 * with multiple classes (Borrower, Staff, Loan, Library) and are tested in
 * Integration Testing section.
 */
public class BookTests {

    private Book book;

    @Before
    public void setUp() {
        // Reset ID counter for consistent testing
        Book.setIDCount(0);

        // Create a test book
        book = new Book(-1, "Test Book", "Testing", "Test Author", false);
    }

    // ==================== Constructor & ID Tests ====================

    @Test
    public void testConstructor_WithAutoGeneratedId() {
        // Test constructor with -1 (auto-generate ID)
        Book.setIDCount(0);
        Book b = new Book(-1, "Title", "Subject", "Author", false);

        assertEquals(1, b.getID());
        assertEquals("Title", b.getTitle());
        assertEquals("Subject", b.getSubject());
        assertEquals("Author", b.getAuthor());
        assertFalse(b.getIssuedStatus());
    }

    @Test
    public void testConstructor_WithSpecificId() {
        // Test constructor with specific ID
        Book b = new Book(100, "Title", "Subject", "Author", true);

        assertEquals(100, b.getID());
        assertTrue(b.getIssuedStatus());
    }

    @Test
    public void testConstructor_InitializesHoldRequestOperations() {
        // Verify that HoldRequestOperations is initialized
        assertNotNull(book.getHoldRequestOperations());
        assertNotNull(book.getHoldRequests());
        assertTrue(book.getHoldRequests().isEmpty());
    }

    // ==================== Getter Tests ====================

    @Test
    public void testGetTitle() {
        assertEquals("Test Book", book.getTitle());
    }

    @Test
    public void testGetAuthor() {
        assertEquals("Test Author", book.getAuthor());
    }

    @Test
    public void testGetSubject() {
        assertEquals("Testing", book.getSubject());
    }

    @Test
    public void testGetIssuedStatus_NotIssued() {
        // Book created with issued=false
        assertFalse(book.getIssuedStatus());
    }

    @Test
    public void testGetIssuedStatus_Issued() {
        // Book created with issued=true
        Book issuedBook = new Book(-1, "Title", "Subject", "Author", true);
        assertTrue(issuedBook.getIssuedStatus());
    }

    @Test
    public void testGetID() {
        // ID should be 1 (first book after reset)
        assertEquals(1, book.getID());
    }

    @Test
    public void testGetHoldRequests_InitiallyEmpty() {
        // New book should have no hold requests
        assertTrue(book.getHoldRequests().isEmpty());
        assertEquals(0, book.getHoldRequests().size());
    }

    // ==================== Static ID Counter Tests ====================

    @Test
    public void testIdCounter_Increments() {
        // Test that ID counter increments for each new book
        Book.setIDCount(0);

        Book b1 = new Book(-1, "Book1", "S", "A", false);
        Book b2 = new Book(-1, "Book2", "S", "A", false);
        Book b3 = new Book(-1, "Book3", "S", "A", false);

        assertEquals(1, b1.getID());
        assertEquals(2, b2.getID());
        assertEquals(3, b3.getID());
    }

    @Test
    public void testSetIDCount() {
        // Test setting the ID counter
        Book.setIDCount(50);
        assertEquals(50, Book.getIDCount());

        Book b = new Book(-1, "Title", "S", "A", false);
        assertEquals(51, b.getID());
    }

    @Test
    public void testGetIDCount() {
        Book.setIDCount(100);
        assertEquals(100, Book.getIDCount());
    }

    // ==================== Hold Request Operations Tests ====================

    @Test
    public void testGetHoldRequestOperations_NotNull() {
        // Verify HoldRequestOperations object exists
        assertNotNull(book.getHoldRequestOperations());
    }

    @Test
    public void testGetHoldRequestOperations_SameInstance() {
        // Verify we get the same instance each time
        HoldRequestOperations ops1 = book.getHoldRequestOperations();
        HoldRequestOperations ops2 = book.getHoldRequestOperations();

        assertSame(ops1, ops2);
    }

    // ==================== Edge Cases ====================

    @Test
    public void testConstructor_WithEmptyStrings() {
        // Test that book can be created with empty strings
        Book b = new Book(-1, "", "", "", false);

        assertEquals("", b.getTitle());
        assertEquals("", b.getSubject());
        assertEquals("", b.getAuthor());
    }

    @Test
    public void testConstructor_WithNullStrings() {
        // Test that book can be created with null strings
        Book b = new Book(-1, null, null, null, false);

        assertNull(b.getTitle());
        assertNull(b.getSubject());
        assertNull(b.getAuthor());
    }

    @Test
    public void testConstructor_WithLongStrings() {
        // Test with very long strings (no length validation)
        String longTitle = "A".repeat(1000);
        Book b = new Book(-1, longTitle, "S", "A", false);

        assertEquals(1000, b.getTitle().length());
    }

    @Test
    public void testConstructor_IdZero() {
        // Test with ID = 0 (valid specific ID)
        Book b = new Book(0, "Title", "S", "A", false);
        assertEquals(0, b.getID());
    }

    @Test
    public void testConstructor_NegativeIdOtherThanMinusOne() {
        // Test with negative ID other than -1
        Book b = new Book(-5, "Title", "S", "A", false);

        // Should use -5 as the ID (not auto-generate)
        assertEquals(-5, b.getID());
    }
}